Adds a "quiet" option to silence output to stdout/stderr
patrickdappollonio/kubectl-slice pull request #30
Opened 2022-02-18 17:57 UTC by ianseyer

2022-02-18 18:31 UTC, patrickdappollonio requested changes

2022-02-18 18:31 UTC, patrickdappollonio commented on app.go
> +	rootCommand.Flags().BoolVar(&opts.Quiet, "quiet", "q", false, "if true, no output is written to stdout/err")
This should be:

```suggestion
	rootCommand.Flags().BoolVarP(&opts.Quiet, "quiet", "q", false, "if true, no output is written to stdout/err")
```

The `BoolVar` doesn't support shorthand.

2022-02-18 18:31 UTC, patrickdappollonio commented on slice/execute.go
> +		if !s.Quiet {
```suggestion
		if !s.opts.Quiet {
```

Options are propagated through `s.opts`.

2022-02-22 15:19 UTC, ianseyer commented
Made the changes - how should I retrigger the builds?

2022-02-22 15:22 UTC, patrickdappollonio commented
Sorry, first time contributors require a manual approval. I went ahead and triggered it. If successful, I'll merge.

2022-02-22 15:58 UTC, merged